# Generated by Django 4.0.3 on 2022-10-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_user_company_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_sector',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing'), ('retail', 'Retail business'), ('wholesale', 'Wholesale business'), ('restaurant', 'Restaurant business')], max_length=80),
        ),
    ]
