# Generated by Django 4.0.3 on 2022-10-14 01:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metaData', '0002_alter_othercompany_company_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceDate', models.DateField(default=django.utils.timezone.now)),
                ('ammount', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metaData.item')),
            ],
        ),
    ]
