# Generated by Django 4.0.3 on 2022-10-14 05:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_inventory_is_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='refDate and item composite key',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='referenceDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
