# Generated by Django 4.0.3 on 2022-10-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_inventory_refdate and item composite key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='ammount',
            new_name='amount',
        ),
    ]
