# Generated by Django 4.0.3 on 2022-10-14 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0006_alter_item_registration_date_and_more'),
        ('transaction', '0005_rename_ammount_inventory_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='referenceDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('is_buy', models.BooleanField(blank=True, default=False)),
                ('is_sell', models.BooleanField(blank=True, default=False)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metaData.othercompany')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metaData.item')),
            ],
        ),
    ]
