# Generated by Django 4.0.3 on 2022-10-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_inventory_referencedate_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
