# Generated by Django 4.0.3 on 2022-10-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0011_alter_othercompany_company_sector'),
        ('transaction', '0007_inventory_note'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('referenceDate', 'item')},
        ),
    ]
