# Generated by Django 4.0.3 on 2022-10-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0012_alter_othercompany_company_sector'),
        ('transaction', '0008_alter_inventory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('referenceDate', 'item')},
        ),
    ]
