# Generated by Django 4.0.3 on 2022-10-19 05:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0013_alter_othercompany_company_sector'),
        ('transaction', '0009_alter_transaction_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0)),
                ('itemNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metaData.node')),
            ],
            options={
                'unique_together': {('referenceDate', 'itemNode')},
            },
        ),
    ]
