# Generated by Django 4.0.3 on 2022-10-04 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('is_endItem', models.BooleanField(default=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.IntegerField()),
                ('level', models.IntegerField()),
                ('child_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_item', to='metaData.item')),
                ('end_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_item', to='metaData.item')),
                ('parent_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_item', to='metaData.item')),
            ],
        ),
    ]
