# Generated by Django 4.0.3 on 2022-10-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercompany',
            name='company_sector',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing'), ('retail', 'Retail business'), ('wholesale', 'Wholesale business'), ('restaurant', 'Restaurant business')], max_length=80, null=True),
        ),
    ]
