# Generated by Django 4.0.3 on 2022-10-12 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metaData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_sector', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('restaurant', 'Restaurant business'), ('wholesale', 'Wholesale business'), ('retail', 'Retail business')], max_length=80, null=True)),
                ('vendor_phoneNum', models.CharField(max_length=200)),
                ('vendor_address', models.CharField(max_length=300)),
                ('is_seller', models.BooleanField()),
                ('is_purchaser', models.BooleanField()),
                ('vendor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
