# Generated by Django 4.0.3 on 2022-10-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
