# Generated by Django 4.0.3 on 2022-10-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0002_othercompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='othercompany',
            old_name='vendor_address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='othercompany',
            old_name='vendor_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='othercompany',
            old_name='vendor_phoneNum',
            new_name='company_phoneNum',
        ),
        migrations.RenameField(
            model_name='othercompany',
            old_name='vendor_user',
            new_name='company_user',
        ),
        migrations.RenameField(
            model_name='othercompany',
            old_name='is_purchaser',
            new_name='is_customer',
        ),
        migrations.RenameField(
            model_name='othercompany',
            old_name='is_seller',
            new_name='is_vendor',
        ),
        migrations.RemoveField(
            model_name='othercompany',
            name='vendor_sector',
        ),
        migrations.AddField(
            model_name='othercompany',
            name='company_sector',
            field=models.CharField(choices=[('wholesale', 'Wholesale business'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail business'), ('restaurant', 'Restaurant business')], max_length=80, null=True),
        ),
    ]
