# Generated by Django 4.0.3 on 2022-10-12 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metaData', '0003_rename_vendor_address_othercompany_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercompany',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myCompany', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='othercompany',
            name='company_sector',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing'), ('restaurant', 'Restaurant business'), ('retail', 'Retail business'), ('wholesale', 'Wholesale business')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='othercompany',
            name='company_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otherCompany', to=settings.AUTH_USER_MODEL),
        ),
    ]
