# Generated by Django 4.0.3 on 2022-10-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0004_othercompany_user_alter_othercompany_company_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othercompany',
            name='company_user',
        ),
        migrations.AlterField(
            model_name='othercompany',
            name='company_sector',
            field=models.CharField(choices=[('retail', 'Retail business'), ('wholesale', 'Wholesale business'), ('restaurant', 'Restaurant business'), ('manufacturing', 'Manufacturing')], max_length=80, null=True),
        ),
    ]
