# Generated by Django 4.0.3 on 2022-10-14 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0005_alter_othercompany_company_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='othercompany',
            name='company_sector',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing'), ('retail', 'Retail business'), ('restaurant', 'Restaurant business'), ('wholesale', 'Wholesale business')], max_length=80, null=True),
        ),
    ]
