# Generated by Django 4.0.3 on 2022-10-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0005_remove_othercompany_company_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercompany',
            name='company_sector',
            field=models.CharField(choices=[('wholesale', 'Wholesale business'), ('restaurant', 'Restaurant business'), ('retail', 'Retail business'), ('manufacturing', 'Manufacturing')], max_length=80, null=True),
        ),
    ]
