# Generated by Django 4.0.3 on 2022-10-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0006_alter_othercompany_company_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercompany',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='othercompany',
            name='company_sector',
            field=models.CharField(choices=[('retail', 'Retail business'), ('restaurant', 'Restaurant business'), ('wholesale', 'Wholesale business'), ('manufacturing', 'Manufacturing')], max_length=80, null=True),
        ),
    ]
