# Generated by Django 4.0.3 on 2022-10-13 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0009_remove_item_depth_remove_item_numchild_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercompany',
            name='company_sector',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing'), ('retail', 'Retail business'), ('wholesale', 'Wholesale business'), ('restaurant', 'Restaurant business')], max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metaData.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
