# Generated by Django 4.0.3 on 2022-10-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0010_alter_othercompany_company_sector_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercompany',
            name='company_sector',
            field=models.CharField(choices=[('restaurant', 'Restaurant business'), ('retail', 'Retail business'), ('manufacturing', 'Manufacturing'), ('wholesale', 'Wholesale business')], max_length=80, null=True),
        ),
    ]
