# Generated by Django 4.0.3 on 2022-10-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metaData', '0012_alter_othercompany_company_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercompany',
            name='company_sector',
            field=models.CharField(choices=[('wholesale', 'Wholesale business'), ('retail', 'Retail business'), ('restaurant', 'Restaurant business'), ('manufacturing', 'Manufacturing')], max_length=80, null=True),
        ),
    ]
