# Generated by Django 4.0.3 on 2022-10-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSignIn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_sector',
            field=models.CharField(choices=[('restaurant', 'Restaurant business'), ('wholesale', 'Wholesale business'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail business')], max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='representative_phone',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
