# Generated by Django 4.0.3 on 2022-10-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preSignIn', '0002_alter_user_company_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_sector',
            field=models.CharField(choices=[('retail', 'Retail business'), ('wholesale', 'Wholesale business'), ('restaurant', 'Restaurant business'), ('manufacturing', 'Manufacturing')], max_length=80),
        ),
    ]
